### ISSUE TITLE
When Switch to another app, your demo crashed. In my app, it restarted while normal situation just resume

### ISSUE THREAD

**Issue by 9h0st** [hotchemi/PermissionsDispatcher#203]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: permissions.dispatcher.sample, PID: 10374
                                                                               java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                                   at android.hardware.Camera.setPreviewSurface(Native Method)
                                                                                   at android.hardware.Camera.setPreviewDisplay(Camera.java:648)
                                                                                   at permissions.dispatcher.sample.camera.CameraPreview.surfaceCreated(CameraPreview.java:65)`

And my phone is moto new x ;app sdk 23;Android version:6.0

**Comment by hotchemi** [comment]
@9h0st Thx for your report. It's not a fault of the library itself but seems sample app has a bug.
