### ISSUE TITLE
Device is XiaoMi ,Check the default permissions  java.lang.IllegalArgumentException: Unknown operation string: null

### ISSUE THREAD

**Issue by lftx** [hotchemi/PermissionsDispatcher#244]
```
AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: permissions.dispatcher.sample, PID: 8940
                                                                             java.lang.IllegalArgumentException: Unknown operation string: null
                                                                                 at android.app.AppOpsManager.strOpToOp(AppOpsManager.java:1464)
                                                                                 at android.app.AppOpsManager.checkOp(AppOpsManager.java:1486)
                                                                                 at permissions.dispatcher.PermissionUtils.hasSelfPermissionForXiaomi(PermissionUtils.java:115)
                                                                                 at permissions.dispatcher.PermissionUtils.hasSelfPermission(PermissionUtils.java:101)
                                                                                 at permissions.dispatcher.PermissionUtils.hasSelfPermissions(PermissionUtils.java:81)
                                                                                 at permissions.dispatcher.sample.MainActivityPermissionsDispatcher.showNetWorkWithCheck(MainActivityPermissionsDispatcher.java:52)
                                                                                 at permissions.dispatcher.sample.MainActivity.onClick(MainActivity.java:41)
                                                                                 at android.view.View.performClick(View.java:5207)
                                                                                 at android.view.View$PerformClick.run(View.java:21177)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)

```

Modify ：

```java
 private static boolean hasSelfPermissionForXiaomi(Context context, String permission) {
        AppOpsManager appOpsManager = (AppOpsManager) context.getSystemService(Context.APP_OPS_SERVICE);
        String op = AppOpsManager.permissionToOp(permission);
        if (!TextUtils.isEmpty(op)) {
            int checkOp = appOpsManager.checkOp(op, Process.myUid(), context.getPackageName());
            return checkOp == AppOpsManager.MODE_ALLOWED && ActivityCompat.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;
        }
        return true;
    }
```

**Comment by shiraji** [comment]
Here is the better format of above code.

```java
private static boolean hasSelfPermissionForXiaomi(Context context, String permission) {
    AppOpsManager appOpsManager = (AppOpsManager) context.getSystemService(Context.APP_OPS_SERVICE);
    String op = AppOpsManager.permissionToOp(permission);
    if (!TextUtils.isEmpty(op)) {
        int checkOp = appOpsManager.checkOp(op, Process.myUid(), context.getPackageName());
        return checkOp == AppOpsManager.MODE_ALLOWED && ActivityCompat.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;
    }
    return true;
}
```

Does anyone confirm this method is correct?

I have additional questions:

* Are you sure `return true;` is correct? Isn't it `return ActivityCompat.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;`?
* Can we use `checkOpNoThrow` instead of using `checkOp`?

**Comment by hotchemi** [comment]
@shiraji 's suggestion is much more reasonable. I think when `permissionToOp` returns null we can return false in the method?

**Comment by hotchemi** [comment]
Btw I just found compat class...who knows!
https://developer.android.com/reference/android/support/v4/app/AppOpsManagerCompat.html#permissionToOp(java.lang.String)

**Comment by aurae** [comment]
That Compat class also seems to return `null`. Amazing! Yeah, @shiraji's suggestion looks good to me as well.

**Comment by shiraji** [comment]
Here is the all expected changes.

```java
    private static boolean hasSelfPermission(Context context, String permission) {
        // * Can we replace checking M with checking KITKAT? Now permissionToOp is in support library and `checkOpNoThrow` (and `checkOp`) is added in API level 19.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT && "Xiaomi".equalsIgnoreCase(Build.MANUFACTURER)) {
            return hasSelfPermissionForXiaomi(context, permission);
        }
        try {
            return checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;
        } catch (RuntimeException t) {
            return false;
        }
    }

    @TargetApi(Build.VERSION_CODES.KITKAT) // Now target api is KITKAT
    private static boolean hasSelfPermissionForXiaomi(Context context, String permission) {
        // * Can we ignore the case getSystemService returns null or return an instance that is not subclass of AppOpsManager?
        AppOpsManager appOpsManager = (AppOpsManager) context.getSystemService(Context.APP_OPS_SERVICE);

        // Use AppOpsManagerCompat instead
        String op = AppOpsManagerCompat.permissionToOp(permission);

        // Replace TextUtils with null check, since I don't want to depends on TextUtils for just checking "op" is null. empty won't happen according to the doc.
        // Use checkOpNoThrow instead
        // watch out for the combination of || and &&.
        // * Shouldn't we use PermissionChecker#checkSelfPermission, instead of using ActivityCompat#checkSelfPermission?
        return (op == null || appOpsManager.checkOpNoThrow(op, Process.myUid(), context.getPackageName()) == AppOpsManager.MODE_ALLOWED) && ActivityCompat.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;
    }
```

Three questions:

* Can we replace checking M with checking KITKAT? Now `permissionToOp` is in support library and `checkOpNoThrow` (and `checkOp`) is added in API level 19.
* Can we ignore the case `getSystemService` returns null or an instance that is not subclass of `AppOpsManager`?
* Shouldn't we use `PermissionChecker#checkSelfPermission`, instead of using `ActivityCompat#checkSelfPermission`?

By the way, I googled about Xiaomi's runtime permission code and found out PermissionsDispatcher is the only library it takes care of. Also, there were almost none of the information that talks about the best practice of handling runtime permissions. I was wondering how developers for Xiaomi survive...

**Comment by hotchemi** [comment]
Sorry I said something wrong...I think if Xiaomi is using `AppOpsManager` there is no meaning to use compat class right?
And yeh, we should use `PermissionChecker#checkSelfPermission`!

Anyway let me handle this issue.

**Comment by hotchemi** [comment]
One thing I'm worried about is when `permissionToOp` returns null is it supposed to be false or true? @lftx

**Comment by lftx** [comment]
I think it should be True,I test on Xiaomi 5 , permissionToOp returns null when use Normal permissions 
@hotchemi

**Comment by hotchemi** [comment]
@lftx Sorry let me clarify, `Normal permission` means the permission that don't need to request grant right? I checked [AOSP](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/app/AppOpsManager.java#342) and it turned out that it has permission list to be requested to user.

**Comment by lftx** [comment]
such as "android.permission.INTERNET" return null  @hotchemi

**Comment by lftx** [comment]
May be I have no description is clear, I am using this method to check all permissions

**Comment by hotchemi** [comment]
@lftx I think you don't have to check all permissions. You can find permissions that you have to address with https://github.com/hotchemi/m-permissions-checker.
So this countermeasure is theoretically not necessary(if permissionToOp returns null then permissions are not needed to be requested to user, they're just normal)...

**Comment by lftx** [comment]
OK，thanks

**Comment by hotchemi** [comment]
My pleasure.
But I'll add some tiny improvements related to this issue. So let me keep.
