### ISSUE TITLE
ActivityNotFoundException when ActivityCompat.requestPermissions() is called within the generated class

### ISSUE THREAD

**Issue by jameskobayashimob** [hotchemi/PermissionsDispatcher#288]
Seeing an ActivityNotFoundException being thrown when the generated class' "withCheck" method is called. Seems be that the device doesn't have an activity that can handle the intent created, does this mean that the device doesn't have a way to manage permissions?

Right now I'll have to check if an activity exists that can support the intent prior to making the withCheck call, which seems like something the generated class could handle and redirect.

Lib version: 2.3.0
Device: Zenphone 2 running android 6.0

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1634)
	at android.app.Activity.startActivityForResult(Activity.java:4633)
	at android.app.Activity.requestPermissions(Activity.java:3899)
	at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
...
```

**Comment by aurae** [comment]
Thanks for your report! This is highly unexpected, and I've never personally expected this issue ever, nor encountered a device that runs API23+ but doesn't handle Runtime Permissions!? Would you mind setting up a Runtime Permissions check flow without using PD, and only using "requestPermissions", and see if that fails as well? Do you have any apps on that phone that do require Runtime Permissions and work?

In any case, your observation seems to be correct, it seems like there is no System Activity to handle the request (which would raise the dialog asking for consent to grant the permission otherwise, I suppose). My quick Google-fu didn't yield any particularly useful results either, but I'm unsure as to how we should go about this. @hotchemi @shiraji, do we really need to test the device capability and call "onPermissionDenied" if the device can't handle it?

**Comment by hotchemi** [comment]
@jameskobayashimob Sorry for the late, can you reproduce the bug with our [sample](https://github.com/hotchemi/PermissionsDispatcher/tree/master/sample) module on the device?
If you can reproduce that's a fault of hardware manufacturer, so I recommend you to catch `ActivityNotFoundException` and show an error message. But ASUS is one of the capable hardware manufacturer of Android so I hope they didn't manipulate such a thing.
@aurae Thx for your quick catch! I think it's okay not to address like this case because it makes hard for developers to realize the problem!

**Comment by hotchemi** [comment]
@jameskobayashimob any update?

**Comment by hotchemi** [comment]
@jameskobayashimob we're not able to proceed investigation about the issue so let me close. Please reopen if needed.

**Comment by AkiraKobayashi** [comment]
Hey, sorry for the late update, I should've mentioned that I do not have the device on hand so unfortunately I'm unable to different scenarios out. For the time being however yes, I have wrapped every call to the generated class/methods.

**Comment by jameskobayashimob** [comment]
Hey, sorry for the late reply. I forgot to mention that I don't have the device in question on hand, so unfortunately I'm not able to investigate any of these scenarios. In the meantime, I have a try/catch to simply avoid crashing wrapped around every call to the generated classes.

**Comment by tracyliu1** [comment]
hello,guys... unfortunately,I have the same Issue too. 
I didn`t use the PD,just use ActivityCompat.requestPermissions()（the basic way） to request permission.
the device is a TVbox(set top box),the SDK is provided by Amlogic.I have the same log as @jameskobayashimob.

**Comment by hotchemi** [comment]
@tracyliu1 Wow thx for your info. Sorry I've never heard about TvBox and Amlogic...what's that?
And if ActivityCompat.requestPermissions() merely returns wrong result, we gotta send a bug report to b.android.com?

**Comment by guofeng007** [comment]
we have met the same exception , sounds like no solution

**Comment by LiDaQiang2016** [comment]
we have met the same exception , sounds like no solution
