### ISSUE TITLE
duplicate entry: permissions/dispatcher/GrantableRequest.class

### ISSUE THREAD

**Issue by john1jan** [hotchemi/PermissionsDispatcher#77]
I am getting this error when i build using gradle

Full stacktrace:
```sh
Caused by: org.gradle.api.UncheckedIOException: java.util.zip.ZipException: duplicate entry: permissions/dispatcher/GrantableRequest.class
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

**Comment by aurae** [comment]
Can you share the except of your build.gradle files where you include PermissionsDispatcher?

**Comment by john1jan** [comment]
Sorry My bad, I declared permission-dispatcher wrongly. I was using 'compile' instead of apt like below

 compile 'com.github.hotchemi:permissionsdispatcher:2.0.3'
 compile  'com.github.hotchemi:permissionsdispatcher-processor:2.0.3'

instead of 
 compile 'com.github.hotchemi:permissionsdispatcher:2.0.3'
 apt 'com.github.hotchemi:permissionsdispatcher-processor:2.0.3'

Changed to 'apt it worked fine. Thanks

**Comment by hotchemi** [comment]
@john1jan Alright, thanks for your adopting.

**Comment by john1jan** [comment]
Thanks for developing this great library it makes life easier with Marshmallow.
